apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luke-api
  template:
    metadata:
      labels:
        app: luke-api
    spec:
      containers:
      - name: luke-api
        image: us-docker.pkg.dev/cit262team/luke-api/api-tests
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.2"
            memory: "300Mi"
          requests:
            cpu: "0.1"
            memory: "150Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 10
